version: "3.7"
services:
  api_service:
    image: order-book:latest
    container_name: orderbook-service
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: 'postgres:13.1-alpine'
    container_name: orderbook-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=orderbook